import { Country } from "./types";

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", lat: 33.93, lng: 67.71, continent: "Asia" },
  { code: "AL", name: "Albania", lat: 41.15, lng: 20.17, continent: "Europe" },
  { code: "DZ", name: "Algeria", lat: 28.03, lng: 1.66, continent: "Africa" },
  { code: "AO", name: "Angola", lat: -11.20, lng: 17.87, continent: "Africa" },
  { code: "AR", name: "Argentina", lat: -38.42, lng: -63.62, continent: "South America" },
  { code: "AM", name: "Armenia", lat: 40.07, lng: 45.04, continent: "Asia" },
  { code: "AU", name: "Australia", lat: -25.27, lng: 133.78, continent: "Oceania" },
  { code: "AT", name: "Austria", lat: 47.52, lng: 14.55, continent: "Europe" },
  { code: "AZ", name: "Azerbaijan", lat: 40.14, lng: 47.58, continent: "Asia" },
  { code: "BD", name: "Bangladesh", lat: 23.68, lng: 90.36, continent: "Asia" },
  { code: "BY", name: "Belarus", lat: 53.71, lng: 27.95, continent: "Europe" },
  { code: "BE", name: "Belgium", lat: 50.50, lng: 4.47, continent: "Europe" },
  { code: "BZ", name: "Belize", lat: 17.19, lng: -88.50, continent: "North America" },
  { code: "BJ", name: "Benin", lat: 9.31, lng: 2.32, continent: "Africa" },
  { code: "BT", name: "Bhutan", lat: 27.51, lng: 90.43, continent: "Asia" },
  { code: "BO", name: "Bolivia", lat: -16.29, lng: -63.59, continent: "South America" },
  { code: "BA", name: "Bosnia and Herzegovina", lat: 43.92, lng: 17.68, continent: "Europe" },
  { code: "BW", name: "Botswana", lat: -22.33, lng: 24.68, continent: "Africa" },
  { code: "BR", name: "Brazil", lat: -14.24, lng: -51.93, continent: "South America" },
  { code: "BN", name: "Brunei", lat: 4.54, lng: 114.73, continent: "Asia" },
  { code: "BG", name: "Bulgaria", lat: 42.73, lng: 25.49, continent: "Europe" },
  { code: "BF", name: "Burkina Faso", lat: 12.36, lng: -1.54, continent: "Africa" },
  { code: "BI", name: "Burundi", lat: -3.37, lng: 29.92, continent: "Africa" },
  { code: "CV", name: "Cape Verde", lat: 16.00, lng: -24.01, continent: "Africa" },
  { code: "KH", name: "Cambodia", lat: 12.57, lng: 104.99, continent: "Asia" },
  { code: "CM", name: "Cameroon", lat: 3.85, lng: 11.50, continent: "Africa" },
  { code: "CA", name: "Canada", lat: 56.13, lng: -106.35, continent: "North America" },
  { code: "CF", name: "Central African Republic", lat: 6.61, lng: 20.94, continent: "Africa" },
  { code: "TD", name: "Chad", lat: 15.45, lng: 18.73, continent: "Africa" },
  { code: "CL", name: "Chile", lat: -35.68, lng: -71.54, continent: "South America" },
  { code: "CN", name: "China", lat: 35.86, lng: 104.20, continent: "Asia" },
  { code: "CO", name: "Colombia", lat: 4.57, lng: -74.30, continent: "South America" },
  { code: "KM", name: "Comoros", lat: -11.64, lng: 43.33, continent: "Africa" },
  { code: "CG", name: "Republic of Congo", lat: -0.23, lng: 15.83, continent: "Africa" },
  { code: "CD", name: "DR Congo", lat: -4.04, lng: 21.76, continent: "Africa" },
  { code: "CR", name: "Costa Rica", lat: 9.75, lng: -83.75, continent: "North America" },
  { code: "HR", name: "Croatia", lat: 45.10, lng: 15.20, continent: "Europe" },
  { code: "CU", name: "Cuba", lat: 21.52, lng: -77.78, continent: "North America" },
  { code: "CY", name: "Cyprus", lat: 35.13, lng: 33.43, continent: "Asia" },
  { code: "CZ", name: "Czech Republic", lat: 49.82, lng: 15.47, continent: "Europe" },
  { code: "DK", name: "Denmark", lat: 56.26, lng: 9.50, continent: "Europe" },
  { code: "DJ", name: "Djibouti", lat: 11.83, lng: 42.59, continent: "Africa" },
  { code: "DO", name: "Dominican Republic", lat: 18.74, lng: -70.16, continent: "North America" },
  { code: "EC", name: "Ecuador", lat: -1.83, lng: -78.18, continent: "South America" },
  { code: "EG", name: "Egypt", lat: 26.82, lng: 30.80, continent: "Africa" },
  { code: "SV", name: "El Salvador", lat: 13.79, lng: -88.90, continent: "North America" },
  { code: "GQ", name: "Equatorial Guinea", lat: 1.65, lng: 10.27, continent: "Africa" },
  { code: "ER", name: "Eritrea", lat: 15.18, lng: 39.78, continent: "Africa" },
  { code: "EE", name: "Estonia", lat: 58.60, lng: 25.01, continent: "Europe" },
  { code: "SZ", name: "Eswatini", lat: -26.52, lng: 31.47, continent: "Africa" },
  { code: "ET", name: "Ethiopia", lat: 9.15, lng: 40.49, continent: "Africa" },
  { code: "FJ", name: "Fiji", lat: -17.71, lng: 178.07, continent: "Oceania" },
  { code: "FI", name: "Finland", lat: 61.92, lng: 25.75, continent: "Europe" },
  { code: "FR", name: "France", lat: 46.23, lng: 2.21, continent: "Europe" },
  { code: "GA", name: "Gabon", lat: -0.80, lng: 11.61, continent: "Africa" },
  { code: "GM", name: "Gambia", lat: 13.44, lng: -15.31, continent: "Africa" },
  { code: "GE", name: "Georgia", lat: 42.32, lng: 43.36, continent: "Asia" },
  { code: "DE", name: "Germany", lat: 51.17, lng: 10.45, continent: "Europe" },
  { code: "GH", name: "Ghana", lat: 7.95, lng: -1.02, continent: "Africa" },
  { code: "GR", name: "Greece", lat: 39.07, lng: 21.82, continent: "Europe" },
  { code: "GT", name: "Guatemala", lat: 15.78, lng: -90.23, continent: "North America" },
  { code: "GN", name: "Guinea", lat: 9.95, lng: -11.61, continent: "Africa" },
  { code: "GW", name: "Guinea-Bissau", lat: 11.80, lng: -15.18, continent: "Africa" },
  { code: "GY", name: "Guyana", lat: 4.86, lng: -58.93, continent: "South America" },
  { code: "HT", name: "Haiti", lat: 18.97, lng: -72.29, continent: "North America" },
  { code: "HN", name: "Honduras", lat: 15.20, lng: -86.24, continent: "North America" },
  { code: "HU", name: "Hungary", lat: 47.16, lng: 19.50, continent: "Europe" },
  { code: "IS", name: "Iceland", lat: 64.96, lng: -19.02, continent: "Europe" },
  { code: "IN", name: "India", lat: 20.59, lng: 78.96, continent: "Asia" },
  { code: "ID", name: "Indonesia", lat: -0.79, lng: 113.92, continent: "Asia" },
  { code: "IR", name: "Iran", lat: 32.43, lng: 53.69, continent: "Asia" },
  { code: "IQ", name: "Iraq", lat: 33.22, lng: 43.68, continent: "Asia" },
  { code: "IE", name: "Ireland", lat: 53.41, lng: -8.24, continent: "Europe" },
  { code: "IL", name: "Israel", lat: 31.05, lng: 34.85, continent: "Asia" },
  { code: "IT", name: "Italy", lat: 41.87, lng: 12.57, continent: "Europe" },
  { code: "JM", name: "Jamaica", lat: 18.11, lng: -77.30, continent: "North America" },
  { code: "JP", name: "Japan", lat: 36.20, lng: 138.25, continent: "Asia" },
  { code: "JO", name: "Jordan", lat: 30.59, lng: 36.24, continent: "Asia" },
  { code: "KZ", name: "Kazakhstan", lat: 48.02, lng: 66.92, continent: "Asia" },
  { code: "KE", name: "Kenya", lat: -0.02, lng: 37.91, continent: "Africa" },
  { code: "KI", name: "Kiribati", lat: 1.87, lng: -157.36, continent: "Oceania" },
  { code: "KP", name: "North Korea", lat: 40.34, lng: 127.51, continent: "Asia" },
  { code: "KR", name: "South Korea", lat: 35.91, lng: 127.77, continent: "Asia" },
  { code: "KW", name: "Kuwait", lat: 29.31, lng: 47.48, continent: "Asia" },
  { code: "KG", name: "Kyrgyzstan", lat: 41.20, lng: 74.76, continent: "Asia" },
  { code: "LA", name: "Laos", lat: 19.86, lng: 102.50, continent: "Asia" },
  { code: "LV", name: "Latvia", lat: 56.88, lng: 24.60, continent: "Europe" },
  { code: "LB", name: "Lebanon", lat: 33.85, lng: 35.86, continent: "Asia" },
  { code: "LS", name: "Lesotho", lat: -29.61, lng: 28.23, continent: "Africa" },
  { code: "LR", name: "Liberia", lat: 6.43, lng: -9.43, continent: "Africa" },
  { code: "LY", name: "Libya", lat: 26.34, lng: 17.23, continent: "Africa" },
  { code: "LI", name: "Liechtenstein", lat: 47.17, lng: 9.56, continent: "Europe" },
  { code: "LT", name: "Lithuania", lat: 55.17, lng: 23.88, continent: "Europe" },
  { code: "LU", name: "Luxembourg", lat: 49.82, lng: 6.13, continent: "Europe" },
  { code: "MG", name: "Madagascar", lat: -18.77, lng: 46.87, continent: "Africa" },
  { code: "MW", name: "Malawi", lat: -13.25, lng: 34.30, continent: "Africa" },
  { code: "MY", name: "Malaysia", lat: 4.21, lng: 108.10, continent: "Asia" },
  { code: "MV", name: "Maldives", lat: 3.20, lng: 73.22, continent: "Asia" },
  { code: "ML", name: "Mali", lat: 17.57, lng: -3.99, continent: "Africa" },
  { code: "MT", name: "Malta", lat: 35.94, lng: 14.38, continent: "Europe" },
  { code: "MH", name: "Marshall Islands", lat: 7.11, lng: 171.18, continent: "Oceania" },
  { code: "MR", name: "Mauritania", lat: 21.01, lng: -10.94, continent: "Africa" },
  { code: "MU", name: "Mauritius", lat: -20.35, lng: 57.55, continent: "Africa" },
  { code: "MX", name: "Mexico", lat: 23.63, lng: -102.55, continent: "North America" },
  { code: "FM", name: "Micronesia", lat: 7.43, lng: 150.55, continent: "Oceania" },
  { code: "MD", name: "Moldova", lat: 47.41, lng: 28.37, continent: "Europe" },
  { code: "MC", name: "Monaco", lat: 43.73, lng: 7.41, continent: "Europe" },
  { code: "MN", name: "Mongolia", lat: 46.86, lng: 103.85, continent: "Asia" },
  { code: "ME", name: "Montenegro", lat: 42.71, lng: 19.37, continent: "Europe" },
  { code: "MA", name: "Morocco", lat: 31.79, lng: -7.09, continent: "Africa" },
  { code: "MZ", name: "Mozambique", lat: -18.67, lng: 35.53, continent: "Africa" },
  { code: "MM", name: "Myanmar", lat: 21.92, lng: 95.96, continent: "Asia" },
  { code: "NA", name: "Namibia", lat: -22.96, lng: 18.49, continent: "Africa" },
  { code: "NR", name: "Nauru", lat: -0.52, lng: 166.93, continent: "Oceania" },
  { code: "NP", name: "Nepal", lat: 28.39, lng: 84.12, continent: "Asia" },
  { code: "NL", name: "Netherlands", lat: 52.13, lng: 5.29, continent: "Europe" },
  { code: "NZ", name: "New Zealand", lat: -40.90, lng: 174.89, continent: "Oceania" },
  { code: "NI", name: "Nicaragua", lat: 12.87, lng: -85.21, continent: "North America" },
  { code: "NE", name: "Niger", lat: 17.61, lng: 8.08, continent: "Africa" },
  { code: "NG", name: "Nigeria", lat: 9.08, lng: 8.68, continent: "Africa" },
  { code: "MK", name: "North Macedonia", lat: 41.61, lng: 21.75, continent: "Europe" },
  { code: "NO", name: "Norway", lat: 60.47, lng: 8.47, continent: "Europe" },
  { code: "OM", name: "Oman", lat: 21.51, lng: 55.92, continent: "Asia" },
  { code: "PK", name: "Pakistan", lat: 30.38, lng: 69.35, continent: "Asia" },
  { code: "PW", name: "Palau", lat: 7.52, lng: 134.58, continent: "Oceania" },
  { code: "PA", name: "Panama", lat: 8.54, lng: -80.78, continent: "North America" },
  { code: "PG", name: "Papua New Guinea", lat: -6.31, lng: 143.96, continent: "Oceania" },
  { code: "PY", name: "Paraguay", lat: -23.44, lng: -58.44, continent: "South America" },
  { code: "PE", name: "Peru", lat: -9.19, lng: -75.02, continent: "South America" },
  { code: "PH", name: "Philippines", lat: 12.88, lng: 121.77, continent: "Asia" },
  { code: "PL", name: "Poland", lat: 51.92, lng: 19.15, continent: "Europe" },
  { code: "PT", name: "Portugal", lat: 39.40, lng: -8.22, continent: "Europe" },
  { code: "QA", name: "Qatar", lat: 25.35, lng: 51.18, continent: "Asia" },
  { code: "RO", name: "Romania", lat: 45.94, lng: 24.97, continent: "Europe" },
  { code: "RU", name: "Russia", lat: 61.52, lng: 105.32, continent: "Europe" },
  { code: "RW", name: "Rwanda", lat: -1.94, lng: 29.87, continent: "Africa" },
  { code: "KN", name: "Saint Kitts and Nevis", lat: 17.36, lng: -62.78, continent: "North America" },
  { code: "LC", name: "Saint Lucia", lat: 13.91, lng: -60.98, continent: "North America" },
  { code: "VC", name: "Saint Vincent and the Grenadines", lat: 12.98, lng: -61.29, continent: "North America" },
  { code: "WS", name: "Samoa", lat: -13.76, lng: -172.10, continent: "Oceania" },
  { code: "SM", name: "San Marino", lat: 43.94, lng: 12.46, continent: "Europe" },
  { code: "ST", name: "Sao Tome and Principe", lat: 0.19, lng: 6.61, continent: "Africa" },
  { code: "SA", name: "Saudi Arabia", lat: 23.89, lng: 45.08, continent: "Asia" },
  { code: "SN", name: "Senegal", lat: 14.50, lng: -14.45, continent: "Africa" },
  { code: "RS", name: "Serbia", lat: 44.02, lng: 21.01, continent: "Europe" },
  { code: "SC", name: "Seychelles", lat: -4.68, lng: 55.49, continent: "Africa" },
  { code: "SL", name: "Sierra Leone", lat: 8.46, lng: -11.78, continent: "Africa" },
  { code: "SG", name: "Singapore", lat: 1.35, lng: 103.82, continent: "Asia" },
  { code: "SK", name: "Slovakia", lat: 48.67, lng: 19.70, continent: "Europe" },
  { code: "SI", name: "Slovenia", lat: 46.15, lng: 14.99, continent: "Europe" },
  { code: "SB", name: "Solomon Islands", lat: -9.65, lng: 160.16, continent: "Oceania" },
  { code: "SO", name: "Somalia", lat: 5.15, lng: 46.20, continent: "Africa" },
  { code: "ZA", name: "South Africa", lat: -30.56, lng: 22.94, continent: "Africa" },
  { code: "SS", name: "South Sudan", lat: 6.88, lng: 31.31, continent: "Africa" },
  { code: "ES", name: "Spain", lat: 40.46, lng: -3.75, continent: "Europe" },
  { code: "LK", name: "Sri Lanka", lat: 7.87, lng: 80.77, continent: "Asia" },
  { code: "SD", name: "Sudan", lat: 12.86, lng: 30.22, continent: "Africa" },
  { code: "SR", name: "Suriname", lat: 3.92, lng: -56.03, continent: "South America" },
  { code: "SE", name: "Sweden", lat: 60.13, lng: 18.64, continent: "Europe" },
  { code: "CH", name: "Switzerland", lat: 46.82, lng: 8.23, continent: "Europe" },
  { code: "SY", name: "Syria", lat: 34.80, lng: 38.99, continent: "Asia" },
  { code: "TW", name: "Taiwan", lat: 23.70, lng: 121.00, continent: "Asia" },
  { code: "TJ", name: "Tajikistan", lat: 38.86, lng: 71.28, continent: "Asia" },
  { code: "TZ", name: "Tanzania", lat: -6.37, lng: 34.89, continent: "Africa" },
  { code: "TH", name: "Thailand", lat: 15.87, lng: 100.99, continent: "Asia" },
  { code: "TL", name: "Timor-Leste", lat: -8.87, lng: 125.73, continent: "Asia" },
  { code: "TG", name: "Togo", lat: 8.62, lng: 0.82, continent: "Africa" },
  { code: "TO", name: "Tonga", lat: -21.18, lng: -175.20, continent: "Oceania" },
  { code: "TT", name: "Trinidad and Tobago", lat: 10.69, lng: -61.22, continent: "North America" },
  { code: "TN", name: "Tunisia", lat: 33.89, lng: 9.54, continent: "Africa" },
  { code: "TR", name: "Turkey", lat: 38.96, lng: 35.24, continent: "Asia" },
  { code: "TM", name: "Turkmenistan", lat: 38.97, lng: 59.56, continent: "Asia" },
  { code: "TV", name: "Tuvalu", lat: -7.11, lng: 177.64, continent: "Oceania" },
  { code: "UG", name: "Uganda", lat: 1.37, lng: 32.29, continent: "Africa" },
  { code: "UA", name: "Ukraine", lat: 48.38, lng: 31.17, continent: "Europe" },
  { code: "AE", name: "United Arab Emirates", lat: 23.42, lng: 53.85, continent: "Asia" },
  { code: "GB", name: "United Kingdom", lat: 55.38, lng: -3.44, continent: "Europe" },
  { code: "US", name: "United States", lat: 37.09, lng: -95.71, continent: "North America" },
  { code: "UY", name: "Uruguay", lat: -32.52, lng: -55.77, continent: "South America" },
  { code: "UZ", name: "Uzbekistan", lat: 41.38, lng: 64.59, continent: "Asia" },
  { code: "VU", name: "Vanuatu", lat: -15.38, lng: 166.96, continent: "Oceania" },
  { code: "VE", name: "Venezuela", lat: 6.42, lng: -66.59, continent: "South America" },
  { code: "VN", name: "Vietnam", lat: 14.06, lng: 108.28, continent: "Asia" },
  { code: "YE", name: "Yemen", lat: 15.55, lng: 48.52, continent: "Asia" },
  { code: "ZM", name: "Zambia", lat: -13.13, lng: 27.85, continent: "Africa" },
  { code: "ZW", name: "Zimbabwe", lat: -19.02, lng: 29.15, continent: "Africa" },
];
